# Generated by Django 2.2.9 on 2020-01-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20200126_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agravos_registrados',
            field=models.ManyToManyField(blank=True, to='modelos.Agravo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pacientes',
            field=models.ManyToManyField(blank=True, to='modelos.Paciente'),
        ),
    ]
